### ISSUE TITLE
ESP8266 Simulation restarting again and again is that ok ?? is that crashing??

### ISSUE THREAD

**Issue by The3ven** [wokwi/esp8266js#1]
OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
Kernel: 4.4.0-19041-Microsoft
Uptime: 2 hours, 35 mins
Packages: 754 (dpkg)
Shell: bash 5.1.16
Terminal: SessionLeader
CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8) @ 2.000GHz
Memory: 7300MiB / 15260MiB
______________________________________________________________________________________________________________________________________________

fire_ubuntu@DESKTOP-COLG88F:~/esp8266js$ npm start -- 0x0 $HELLO_WORLD_PATH/build/bootloader/bootloader.bin 0x8000 $HELLO_WORLD_PATH/build/partitions_singleapp.bin 0x10000 $HELLO_WORLD_PATH/build/hello-world.bin

> @wokwi/esp8266js@0.1.0 start
> ts-node --project tsconfig.ts-node.json cli/cli 0x0 /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/bootloader/bootloader.bin 0x8000 /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/partitions_singleapp.bin 0x10000 /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/hello-world.bin

       __              ,
|  |  /  \  |_/  |  |  |
|/\|  \__/  | \  |/\|  |

Wokwi ESP8266 Emulator CLI

Simulating ESP8266
Loading /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/bootloader/bootloader.bin at 0x0
Loading /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/partitions_singleapp.bin at 0x8000
Loading /home/fire_ubuntu/esp8266js/ESP8266_RTOS_SDK/examples/get-started/hello_world/build/hello-world.bin at 0x10000

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
Restarting in 2 seconds...
Restarting in 1 seconds...
Restarting in 0 seconds...
Restarting now.

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
Restarting in 2 seconds...
Restarting in 1 seconds...
Restarting in 0 seconds...
Restarting now.

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
Restarting in 2 seconds...
Restarting in 1 seconds...
Restarting in 0 seconds...
Restarting now.

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
Restarting in 2 seconds...
Restarting in 1 seconds...
Restarting in 0 seconds...
Restarting now.

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
Restarting in 2 seconds...
Restarting in 1 seconds...
Restarting in 0 seconds...
Restarting now.

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
Unknown SPI Flash command: 100000
Unknown SPI Flash command: 4000000
Unknown SPI Flash command: 4000000
load 0x40100000, len 7544, room 16
tail 8
chksum 0xc3
load 0x3ffe8408, len 24, room 0
tail 8
chksum 0x4a
load 0x3ffe8420, len 3468, room 0
tail 12
chksum 0x79
csum 0x79
I (9) boot: ESP-IDF v3.4-79-gaf0cdc36 2nd stage bootloader
I (9) boot: compile time 18:50:51
I (9) qio_mode: Enabling default flash chip QIO
I (9) boot: SPI Speed      : 40MHz
I (9) boot: SPI Mode       : QIO
I (9) boot: SPI Flash Size : 2MB
I (9) boot: Partition Table:
I (10) boot: ## Label            Usage          Type ST Offset   Length
I (10) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (10) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (10) boot:  2 factory          factory app      00 00 00010000 000f0000
I (11) boot: End of partition table
I (11) esp_image: segment 0: paddr=0x00010010 vaddr=0x40210010 size=0x1ccc8 (117960) map
I (35) esp_image: segment 1: paddr=0x0002cce0 vaddr=0x4022ccd8 size=0x07004 ( 28676) map
I (41) esp_image: segment 2: paddr=0x00033cec vaddr=0x3ffe8000 size=0x00544 (  1348) load
I (42) esp_image: segment 3: paddr=0x00034238 vaddr=0x40100000 size=0x00080 (   128) load
I (42) esp_image: segment 4: paddr=0x000342c0 vaddr=0x40100080 size=0x050c4 ( 20676) load
I (47) boot: Loaded app from partition at offset 0x10000
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...

**Comment by urish** [comment]
Yes, this is okay - it is part of the example program that is running in the simulator.

**Comment by The3ven** [comment]
yeah im just check 
thank you so much,
can we get gui for this??

**Comment by urish** [comment]
Only if you write one ;-)
